const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('gymclipDesktop', {
  isDesktop: true,
  // Local API auth: per-launch random token generated by the main process.
  // Fetched by src/main.tsx before React mounts so every /api request
  // (headers) and media URL (?token=) carries it from the first paint.
  getApiToken: () => ipcRenderer.invoke('auth:get-api-token'),
  // Dynamically-selected backend base URL (host + free port picked at spawn).
  // Fetched by src/main.tsx before React mounts so requests target the real
  // backend port instead of a hardcoded 8000.
  getBackendBaseUrl: () => ipcRenderer.invoke('app:get-backend-base-url'),
  loadApiKey: () => ipcRenderer.invoke('settings:load-api-key'),
  saveApiKey: (apiKey) => ipcRenderer.invoke('settings:save-api-key', apiKey),
  clearApiKey: () => ipcRenderer.invoke('settings:clear-api-key'),
  loadOssCredentials: () => ipcRenderer.invoke('settings:load-oss-credentials'),
  saveOssCredentials: (accessKeyId, accessKeySecret) =>
    ipcRenderer.invoke('settings:save-oss-credentials', accessKeyId, accessKeySecret),
  clearOssCredentials: () => ipcRenderer.invoke('settings:clear-oss-credentials'),
  loadDefaultExportDirectory: () => ipcRenderer.invoke('settings:load-default-export-directory'),
  saveDefaultExportDirectory: (defaultExportDirectory) =>
    ipcRenderer.invoke('settings:save-default-export-directory', defaultExportDirectory),
  loadUploadSettings: () => ipcRenderer.invoke('settings:load-upload-settings'),
  saveUploadSettings: (uploadParallelFiles, uploadPartThreads) =>
    ipcRenderer.invoke('settings:save-upload-settings', uploadParallelFiles, uploadPartThreads),
  selectDirectory: (initialPath) => ipcRenderer.invoke('dialog:select-directory', initialPath),
  selectImportSources: (initialPath) => ipcRenderer.invoke('dialog:select-import-sources', initialPath),
  showSystemNotification: (payload) => ipcRenderer.invoke('notification:show', payload),
  // === Telemetry / Sentry consent (C-5) ===
  getTelemetryConfig: () => ipcRenderer.invoke('telemetry:get-config'),
  setTelemetryConsent: (enabled) => ipcRenderer.invoke('telemetry:set-consent', !!enabled),
  // === Auto-updater (E-5) ===
  onUpdateAvailable: (cb) => ipcRenderer.on('autoUpdater:update-available', (_, info) => cb(info)),
  onDownloadProgress: (cb) => ipcRenderer.on('autoUpdater:download-progress', (_, p) => cb(p)),
  onUpdateDownloaded: (cb) => ipcRenderer.on('autoUpdater:update-downloaded', (_, info) => cb(info)),
  quitAndInstall: () => ipcRenderer.invoke('autoUpdater:quit-and-install'),
});
